console.log('=== Electron Runtime Diagnostic ===')
console.log('process.type:', process.type)
console.log('process.execPath:', process.execPath)
console.log('process.argv:', JSON.stringify(process.argv))
console.log('process.versions.electron:', process.versions.electron)
const e = require('electron')
console.log('require("electron"):', typeof e, String(e).substring(0, 100))
console.log('==================================')
setTimeout(() => process.exit(0), 3000)